name: sipnudge_task
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^26.2.10
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    # lexend font family

    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend/Lexend-Black.ttf
          weight: 900


  # Urbanist font family
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/urbanist/Urbanist-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/urbanist/Urbanist-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/urbanist/Urbanist-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/urbanist/Urbanist-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/urbanist/Urbanist-BlackItalic.ttf
          weight: 900
          style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
